version: '2'
services:
  tomcat:
    build:
      context: .
    image: tomcat
    container_name: tomcat
    restart: always
    privileged: true
    ports:
      - "8080:80"
    volumes:
      #- ./conf/server.xml:/usr/local/tomcat/conf/server.xml
      #- ./webapps:/usr/local/tomcat/webapps
      - ./logs:/usr/local/tomcat/logs
      #- /etc/localtime:/etc/localtime:ro
    mem_limit: 1G
    memswap_limit: 1G
