version: '2'
services:
  tomcat:
    build:
      context: .
    container_name: tomcat
    restart: always
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      #- ./conf/server.xml:/usr/local/tomcat/conf/server.xml
      #- ./webapps:/usr/local/tomcat/webapps
      - ./logs:/usr/local/tomcat/logs
      - /etc/localtime:/etc/localtime:ro
    command: -m 512m
