version: '2'
services:
  tomcat:
    build:
      context: .
    image: tomcat
    container_name: tomcat
    restart: always
    privileged: true
    ports:
      - "80:8080"
    volumes:
      - ./conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./bin/setenv.sh:/usr/local/tomcat/bin/setenv.sh
      #- ./bin/catalina.sh:/usr/local/tomcat/bin/catalina.sh
      - ./webapps:/usr/local/tomcat/webapps
      - ./logs:/usr/local/tomcat/logs
      #- /etc/localtime:/etc/localtime:ro
    mem_limit: 1G
    memswap_limit: 1G
